# Generated by Django 4.1.3 on 2022-11-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
    ]
